apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-serving
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: model-serving
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
