apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-prod
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: model-serving
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: Production
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: prod-key
