auth:
  rootUser: minio
  rootPassword: minio12345

defaultBuckets: "mlflow,data"

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
